spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medicaldb?verifyServerCertificate=false&useSSL=true
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true